name: Keep Render App Awake

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your ping endpoint
        run: |
          echo "Pinging your Render app..."
          curl -sSf https://resu-host-backend.onrender.com/api/ping || echo "Ping failed"
